version: 2
updates:
  - package-ecosystem: "npm"
    allow:
      - dependency-type: "production"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    reviewers:
      - "johannestegner"
